//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoreboard.Wpf {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class scoreboard : global::System.Configuration.ApplicationSettingsBase {
        
        private static scoreboard defaultInstance = ((scoreboard)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new scoreboard())));
        
        public static scoreboard Default {
            get {
                return defaultInstance;
            }
        }
    }
}
